FROM wordpress:6.0.2-php7.4-apache

RUN apt-get update && apt-get -qq --force-yes install cron
COPY wpcron.txt /etc/cron.d/wpcron
RUN chmod 0744 /etc/cron.d/wpcron
RUN crontab /etc/cron.d/wpcron

ENV XDEBUG_PORT 8999
ENV XDEBUG_IDEKEY docker

RUN pecl install "xdebug" \
    && docker-php-ext-enable xdebug

RUN echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.client_port=${XDEBUG_PORT}" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.idekey=${XDEBUG_IDEKEY}" >> /usr/local/etc/php/conf.d/xdebug.ini

CMD cron && apache2-foreground