name: Code validation

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: NPM Install
        run: npm ci
        env:
          CI: true

      - name: Lint
        run: npm run format:check
